GET http://localhost:8080/api/owners

###

GET http://localhost:8080/api/owners/1

###

POST http://localhost:8080/api/owners
Content-Type: application/json

{
  "name": "Właściciel",
  "surname": "Nowy",
  "gender": "MALE"
}

###

PATCH http://localhost:8080/api/owners/7
Content-Type: application/json

{
  "surname": "Jeszczenowszy"
}

###

DELETE http://localhost:8080/api/owners/7

###
###

GET http://localhost:8080/api/animals

###

GET http://localhost:8080/api/animals/1

###

POST http://localhost:8080/api/animals
Content-Type: application/json

{
  "name": "Nowe zwierzątko",
  "species": "WOMBAT",
  "gender": "MALE",
  "ownerId": 3
}

###

PATCH http://localhost:8080/api/animals/7
Content-Type: application/json

{
  "name": "Jeszcze nowsze zwierzątko"
}

###

DELETE http://localhost:8080/api/animals/7