GET http://localhost:8082/api/animals

###

GET http://localhost:8082/api/animals/1

###

POST http://localhost:8082/api/animals
Content-Type: application/json

{
  "name": "Nowe zwierzątko",
  "species": "WOMBAT",
  "gender": "MALE",
  "ownerId": 3
}

###

PATCH http://localhost:8082/api/animals/7
Content-Type: application/json

{
  "name": "Jeszcze nowsze zwierzątko"
}

###

DELETE http://localhost:8082/api/animals/7