GET http://localhost:8081/api/owners

###

GET http://localhost:8081/api/owners/1

###

POST http://localhost:8081/api/owners
Content-Type: application/json

{
  "name": "Właściciel",
  "surname": "Nowy",
  "gender": "MALE"
}

###

PATCH http://localhost:8081/api/owners/7
Content-Type: application/json

{
  "surname": "Jeszczenowszy"
}

###

DELETE http://localhost:8081/api/owners/7